version: '3.2'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ee:latest
    ports:
    - '443:443'
    - '8022:22'
    shm_size: '256m'
    volumes:
    - $GITLAB_HOME/gitlab/config:/etc/gitlab
    - $GITLAB_HOME/gitlab/logs:/var/log/gitlab
    - $GITLAB_HOME/gitlab/data:/var/opt/gitlab
